# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f1293da3db3dab97f457e4a76bee50a0c491d0a78b8079de48fc3eec8fa52b0ed3d7e2331da636a799075f26b104c5bd60ce55a04b23fdbc281cd58c0a03673

test:
  secret_key_base: dc136cabc96856d9410da7bab4d1d05fec66effbbc9a48555efc57aefdca25f390842299bd2671b935dc2675f55de8d243b3ea97031d5cead2d253ec33bf0005

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
